name: "Go Frontend Audit Script Action"
description: "Runs a go script to audit a given repository"

inputs:
  token:
    description: "GitHub token to add commits to pull request."
    required: true

runs:
  using: composite
  steps:
    - name: Run Go Audit Scrip
      uses: docker://yonatanrojas/frontendauditscript:latest

    - name: Post PR Comment
      uses: actions/github-script@v6
      env:
        EVALUATION_TOTAL_SCORE: ${{ env.EVALUATION_TOTAL_SCORE }}
      with:
        GITHUB_TOKEN: ${{ inputs.token }}
        script: |
          const path = require('path');
          const postPrComment = require(path.join(process.env.GITHUB_WORKSPACE, 'scripts/postPRComment.js'));

          const finalScore = process.env.EVALUATION_TOTAL_SCORE

          postPrComment({ github, context, finalScore })
