name: "Go Frontend Audit Script Action"
description: "Runs a Go script to audit a given repository"

inputs:
  token:
    description: "GitHub token to add comments to a pull request."
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.24" # Adjust as needed

    - name: Install Dependencies
      shell: bash
      run: go mod tidy

    - name: Run Go Audit Script
      id: calculate_quality_score
      shell: bash
      env:
        REPO: ${{ github.repository }}
        PR_NUMBER: ${{ github.ref_name }}
        RUN_ID: ${{ github.run_id }}
        OWNER: ${{ github.actor }}
        COMMIT_SHA: ${{ github.sha }}
      run: |
        echo "Running Go audit script..."
        echo $GITHUB_ACTION_PATH
        # go run $GITHUB_ACTION_PATH/calculate_quality_score.go \
        #   "${{ env.REPO }}" \
        #   "${{ env.COMMIT_SHA }}" \
        #   "${{ env.PR_NUMBER }}" \
        #   "${{ env.RUN_ID }}" \
        #   "${{ env.OWNER }}"

    - name: Post PR Comment with Results
      uses: actions/github-script@v6
      with:
        github-token: ${{ inputs.token }}
        script: |
          const path = require('path');
          const postPrComment = require(path.join(process.env.GITHUB_ACTION_PATH, 'post-pr-comment.js'));
