name: "Go Frontend Audit Script Action"
description: "Runs a go script to audit a given repository"

inputs:
  token:
    description: "GitHub token to add commits to pull request."
    required: true

runs:
  using: composite
  steps:
    - name: Run Go Audit Scrip
      uses: docker://yonatanrojas/frontendauditscript:latest

    - name: Debug
      shell: bash
      run: |
        echo -----------DEBUG-------------
        env
        ls -la

    # - name: Echo JS Path
    #   shell: bash
    #   run: |
    #     ls -la
    #     pwd
    #
    # - name: Post PR Comment
    #   uses: actions/github-script@v6
    #   env:
    #     EVALUATION_TOTAL_SCORE: ${{ env.EVALUATION_TOTAL_SCORE }}
    #   with:
    #     github-token: ${{ inputs.token }}
    #     script: |
    #       const path = require('path');
