on:
  push:
    branches: [master]

permissions:
  pull-requests: write
  contents: write

jobs:
  goaction:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Update actions file
        uses: posener/goaction@v1
      - name: Exampe Go run script
        uses: go run ./main.go
